# Default Specification Configuration for ACT Spec Creators
# 
# This configuration provides sensible defaults for creating verification
# specifications from both TorchVision and VNNLIB sources.
#
# Used by: BaseSpecCreator and subclasses (TorchVisionSpecCreator, VNNLibSpecCreator)

# Epsilon values for perturbation-based input specs
# Used for BOX and LINF_BALL input specifications
epsilons:
  - 0.01
  - 0.03
  - 0.05

# Margin values for robustness output specs
# Used for MARGIN_ROBUST output specifications
margins:
  - 0.0

# Input specification types to generate
# Options: BOX, LINF_BALL, LIN_POLY
input_kinds:
  - BOX
  - LINF_BALL

# Output specification types to generate
# Options: LINEAR_LE, TOP1_ROBUST, MARGIN_ROBUST, RANGE
output_kinds:
  - MARGIN_ROBUST

# Spec combination strategy
# Options:
#   - full: All input_specs × all output_specs (cartesian product)
#   - minimal: One input_spec, one output_spec (smallest set)
#   - balanced: Multiple combinations with controlled growth
combination_strategy: balanced

# Balanced strategy parameters (used when strategy = balanced)
balanced_params:
  max_input_specs: 3
  max_output_specs: 2
  max_total_combinations: 6

# Validation settings
validation:
  # Whether to validate specs against model I/O shapes
  validate_shapes: true
  
  # Whether to skip specs that fail validation (vs raising error)
  skip_invalid: true

# TorchVision-specific settings (overridden by torchvision_classification.yaml)
torchvision:
  # Number of samples to use per dataset-model pair
  num_samples: 10
  
  # Starting index in dataset
  start_index: 0
  
  # Dataset split to use
  split: "test"

# VNNLIB-specific settings (overridden by vnnlib_default.yaml)
vnnlib:
  # Maximum instances per category
  max_instances: null  # null = process all instances
  
  # Whether to simplify ONNX models before conversion
  simplify_onnx: true

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  show_progress: true
